### ISSUE TITLE
Command not found - and nothing that looks like it might be a command or script.

### ISSUE THREAD

**Issue by scargill** [kalliope-project/kalliope_starter_en#1]
Raspberry Pi 2

git clone https://github.com/kalliope-project/kalliope_starter_en.git
cd kalliope_starter_en
kalliope start

Ran the last line - Kalliope command not found.

Sure enough in that directory - nothing remotely looking like a Kalliope command.

Do let me know - pete@scargill.org -  I was planning to review this at http://tech.scargill.net

**Comment by Sispheor** [comment]
Have you installed kalliope via pip? Look at the installation doc.

**Comment by scargill** [comment]
Hi

 

In your blog the starter kit make no mention if this whatsoever?? 3 lines to run – and all you get is a directory with nothing to run in it.

 

Pete.

**Comment by Sispheor** [comment]
This is the main repo you have to check before installing a starter kit: https://github.com/kalliope-project/kalliope

**Comment by scargill** [comment]
Tha’ts where I started – the English starter kit - 

 

“Out of the box” – all you have to do is

 

git clone https://github.com/kalliope-project/kalliope_starter_en.git

cd kalliope_starter_en

kalliope star

 

 

and that… doesn’t work..

 

So I went to the METHOD 2 – see other email – errors

 

Pete.

**Comment by Sispheor** [comment]
Like I said in the other thread, you need to follow the complete installation process. This include the pre requisite and the main installation with setup.py.

You can also chat with us directly on our [gitter ](https://gitter.im/kalliope-project/Lobby)if you need assistance.

**Comment by scargill** [comment]
Hmm, nothing in the wAV file…

**Comment by scargill** [comment]
Does this look right to you…

 

pi@raspberrypi:~ $ arecord -l

**** List of CAPTURE Hardware Devices ****

card 1: Device [USB PnP Sound Device], device 0: USB Audio [USB Audio]

  Subdevices: 1/1

  Subdevice #0: subdevice #0

pi@raspberrypi:~ $

 

 

pi@raspberrypi:~ $ aplay -l

**** List of PLAYBACK Hardware Devices ****

card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]

  Subdevices: 8/8

  Subdevice #0: subdevice #0

  Subdevice #1: subdevice #1

  Subdevice #2: subdevice #2

  Subdevice #3: subdevice #3

  Subdevice #4: subdevice #4

  Subdevice #5: subdevice #5

  Subdevice #6: subdevice #6

  Subdevice #7: subdevice #7

card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]

  Subdevices: 1/1

  Subdevice #0: subdevice #0

pi@raspberrypi:~ $

 

 

and hence I made this entry into .asoundrc

 

pcm.!default {

   type asym

   playback.pcm {

     type plug

     slave.pcm "hw:0,0"

   }

   capture.pcm {

     type plug

     slave.pcm "hw:0,1"

   }

}

 

Playback works a treat – microphone – nothing.

**Comment by Sispheor** [comment]
Peter, like I said in the other issue you opened, we've fixed the installation on the last Raspbian image and a lot of bugs in the last release. If you want to give a shot.
I close the issue.
