### ISSUE TITLE
[RESOLVED] - [Brain] Problem asking the date

### ISSUE THREAD

**Issue by odouglsantos** [kalliope-project/kalliope_starter_en#2]
Hello, I made the project clone to start with the Kalliope Project, I was able to use GoogleTTS and Google STT in Brazilian Portuguese, but when I run the Brain say-local-date it does not return to the month, the day of the month, the day of the month. Week and year returns normally. I looked in the files about where the information comes from, but I did not find it. Would you help me?

**Comment by Sispheor** [comment]
Did you take a look to the neuron doc?

Le 22 juil. 2017 01:52, "Douglas Santos" <notifications@github.com> a
écrit :

**Comment by odouglsantos** [comment]
Yes, I have already looked at the documentation. Only the variable {{month}} in systemdate_template.j2 returns empty.

**Comment by Sispheor** [comment]
I just tested. Working for me.

Here is the say template
```
"it's {{ hours }} and {{ minutes }} minute. month number {{month}}"
```

And my audio test
```
2017-07-22 10:26:34,448 :: INFO :: what can i do for you?
Say something!
2017-07-22 10:26:35,755 :: INFO :: Say something!
Google Speech Recognition thinks you said what time is it
2017-07-22 10:26:39,306 :: INFO :: Google Speech Recognition thinks you said what time is it
Order matched in the brain. Running synapse "say-local-date"
2017-07-22 10:26:39,356 :: INFO :: Order matched in the brain. Running synapse "say-local-date"
it's 10 and 26 minute. month number 07
2017-07-22 10:26:39,364 :: INFO :: it's 10 and 26 minute. month number 07
```

**Comment by Sispheor** [comment]
Found the problem, can you update the template and add a zero (0) before each number < 10 ?

Before:
```
{% set month_word = {"1": "january", "2": "february", "3": "march", "4": "april", "5": "may", "6": "june", "7": "july", "8": "august", "9": "september", "10": "october", "11": "november", "12": "december"}[month] | default("") -%}
```

After:
```
{% set month_word = {"01": "january", "02": "february", "03": "march", "04": "april", "05": "may", "06": "june", "07": "july", "08": "august", "09": "september", "10": "october", "11": "november", "12": "december"}[month] | default("") -%}
```

**Comment by odouglsantos** [comment]
Fantastic. I made the change and it worked out here. Thank you very much.

**Comment by Sispheor** [comment]
I have updated the start kit with the fix.
Thanks for the report.
