### ISSUE TITLE
dong sound is not working ??? 

### ISSUE THREAD

**Issue by Amrlol** [kalliope-project/kalliope_starter_en#4]
hey everybody ,  so after calling the  trigger word (kalliope) , i want to hear a dong sound , which i think it's not put to default !! 
so can you show me were to configure it ? @Sispheor

**Comment by Sispheor** [comment]
Instead of asking almost everything at each step, why not trying to read the doc?

The answer of what you are looking for is in the hook system. The default hook is linked to a synapse that make kalliope speaking. Switch it to a synapse that read a mp3 instead.
