### ISSUE TITLE
how to make kalliope give a sound after listening

### ISSUE THREAD

**Issue by angelica101** [kalliope-project/kalliope_starter_en#5]
i've installed kalliope on my raspberry pi 3 model b and it worked yaaaaay

but i've noticed in some youtube videos that after kalliope start listening it gives a sound but in my case it dont give anything so after searching i found something on settings called hook and one of them called on_start_listening is this what i have to config or what?
i saw a previous issue about the same problem but i didn't get it ( noooob :) ) 
so any help !!

note : i'm totally new to this

**Comment by Sispheor** [comment]
Please read the doc. And use the [Gittter chat](https://gitter.im/kalliope-project/Lobby) to get help.

You need to create a synapse and link it to the hook on_start_listening. The synapse will use for example the neuron shell that run "mplayer" to play a mp3.

**Comment by Sispheor** [comment]
Kallippe doc: https://kalliope-project.github.io/kalliope/
